### ISSUE TITLE
Android is not detected on samsung a12

### ISSUE THREAD

**Issue by FreddyMcRay** [jankapunkt/js-detect-os#5]
Platform is detected as linux, running cordova app on samsung a12 (android 10) 
![image](https://user-images.githubusercontent.com/26858004/119122466-34660180-ba37-11eb-8da4-c16791ae3cb0.png)
Running the same app on ios allows to detect platform correctly

**Comment by jankapunkt** [comment]
Hi @FreddyMcRay  Which version of the package do you use?

**Comment by FreddyMcRay** [comment]
Hi @jankapunkt 1.2.0

**Comment by jankapunkt** [comment]
Thank you I will add the platform and useragent to the tests and update the pattern detection

**Comment by jankapunkt** [comment]
Could you please copy/patse the platform and useragent so I can use them in the tests?

**Comment by FreddyMcRay** [comment]
>navigator.platform
"Linux armv8l"

>navigator.userAgent
"Mozilla/5.0 (Linux; Android 10; SM-A125F Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Mobile Safari/537.36"

**Comment by jankapunkt** [comment]
Hey @FreddyMcRay  it auto closed the issue after PR merge :-D

Please install 1.2.1 and check if it works now.

**Comment by jankapunkt** [comment]
@FreddyMcRay did it work out for you?

**Comment by FreddyMcRay** [comment]
I haven't check yet. Will do today, thanks

**Comment by FreddyMcRay** [comment]
Yes, it works
